# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphics.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1664, 1116)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_init_state = QtWidgets.QPushButton(self.centralwidget)
        self.btn_init_state.setGeometry(QtCore.QRect(10, 30, 141, 51))
        self.btn_init_state.setObjectName("btn_init_state")
        self.btn_fin_state = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fin_state.setGeometry(QtCore.QRect(10, 120, 141, 61))
        self.btn_fin_state.setObjectName("btn_fin_state")
        self.pixelmap = QtWidgets.QLabel(self.centralwidget)
        self.pixelmap.setGeometry(QtCore.QRect(170, 10, 1461, 1061))
        self.pixelmap.setText("")
        self.pixelmap.setObjectName("pixelmap")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1664, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_init_state.setText(_translate("MainWindow", "Show Initial State"))
        self.btn_fin_state.setText(_translate("MainWindow", "Show final State"))
